const constantNotify = {
  ACCESS_TOKEN: "F!acHu#k14kjs@nmz",
  REFRESH_TOKEN: "F!acHu#k14kjs@nmz",
  TOKEN_TIME_LIFE: "30d",
  REFRESH_TOKEN_TIME_LIFE: "7d", // 1h (giờ), 7d (ngày)
  // DEFAULT_LIMIT: "",
  // VALIDATE_BODY: "không được để trống",
  ADD_DATA_SUCCESS: "Thêm thành công",
  // ADD_DATA_FAILED: "Thêm thất bại",
  ACCOUNT_FAILED: "Tài khoản không chính xác",
  PASS_FAILED: "Mật khẩu không chính xác",
  // EMAIL_FAILED: "Email không chính xác",
  PASS_OLD_FAILED: "Mật khẩu cũ không chính xác",
  UPDATE_DATA_SUCCESS: "Cập nhật thành công",
  // UPDATE_DATA_FAILED: "Cập nhật thất bại",
  // CONNECT_SUCCESS: "Kết nối thành công",
  DELETE_DATA_SUCCESS: "Xóa thành công",
  // DELETE_DATA_FAILED: "Xóa thất bại",
  ERROR: "Đã xảy ra lỗi",
  // EXPIRED_ON_PASS: "Mật khẩu do hệ thống cấp đã hết hạn",
  ALREADY_EXITS: "đã tồn tại",

  NOT_ACTIVE_ACCOUNT: "Tài khoản đã vị vô hiệu",
  DELETED_ACCOUNT: "Tài khoản đã bị xóa",
  NOT_EXITS: "không tồn tại",
  NOT_DELETE_IMAGE: "Không thể xoá hình ảnh này",
  // IS_NUMBER: "Dữ liệu bắt buộc là số",
  IS_EMAIL: "Dữ liệu là email",

  // VALIDATE_ACCOUNT: "Tài khoản chỉ chứa kí tự thường và số",
  // VALIDATE_EMAIL: "Email không đúng định dạng",
  VALIDATE_PASS:
    "Mật khẩu bao gồm ít nhất 1 kí tự in hoa, chữ, số và không chứa kí tự đặc biệt",
  // CHECK_EMAIL: "Vui lòng kiểm tra email để nhận lại mật khẩu!",
  CHANGE_PASS_SUCCESS: "Thay đổi mật khẩu thành công",
  NOT_EMPTY: "Dữ liệu bắt buộc",

  VALIDATE_NAME_FILE: "Tên file không hợp lệ",
  VALIDATE_PHONE: "Số điện thoại không hợp lệ",
  VALIDATE_FILE_COUNT: "Chỉ có thể upload tối đa",
  VALIDATE_FILE_SIZE: "Kích thước tệp tin không được vượt quá 2MB",
  VALIDATE_FILE_SIZE_WITH_INDEX: "có kích thước vượt quá 2MB",
  VALIDATE_PRICE: "Giá phải lớn hơn 0",
  VALIDATE_PRICE_SALE: "Giá khuyến mãi phải nhỏ hơn giá gốc",
  VALIDATE_DISCOUNT: "Giảm giá phải nhỏ hơn 100%",
  VALIDATE_DATA_LAGER_THAN_0: "Dữ liệu phải lớn hơn 0",
  // VALIDATE_NEWS_SIZE: "Dung lượng news phải nhỏ hơn 20MB",
  SERVER_ERROR: "Máy chủ xảy ra lỗi",
  // NOT_VALID: "không khả dụng",
  MSG_CHANGE_PRICE_SUGGEST: "vừa thay đổi giá đề xuất",
};

module.exports = constantNotify;
